export const data = [
  {
    id: 1,
    From: "Pankaj Kumar",

    subject: "say hellow",
    isRead: true,
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 2,
    isRead: false,
    From: "Sundeep",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 3,
    isRead: true,
    From: "Akash",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 4,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 5,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 6,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 7,
    isRead: true,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 8,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 9,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 10,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 11,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 12,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
  {
    id: 13,
    isRead: false,
    From: "Pankaj Kumar",
    subject: "say hellow",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facili explicabo nesciunt voluptas, excepturi dolor reprehenderit, aut optio necessitatibus culpa architecto laudantium. Quidem, facere consequuntur praesentium dolores molestiae ipsa nostrum quas illo,debitis animi quis assumenda dicta sunt! Ipsum commodi voluptatibus odio consectetur. Nobis, veritatis. Iste dolore quisquam et quidem numquam.",
  },
];
